[package]
name = "docxparser"
version = "0.1.0"
edition = "2024"

[dependencies]
docx-rs = "0.4.18"
docx-rust = "0.1.10"
markdownify = "0.2.1"
pulldown-cmark = "0.13.0"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
